{{- if .Values.errorPage.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-error-pages
  namespace: {{ .Values.namespace.name }}
data:
  custom_error: |
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="https://cloud-web-resources.s3.eu-central-1.amazonaws.com/404_page_resources/pageNotFound.css">

        <link rel="icon" href="/img/newFavicon.svg">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300" rel="stylesheet">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@600" rel="stylesheet">
      
      <title>Your space is not responding</title>
      </head>
      <body>
        <div class="page404"> 
          <div class="logoWrapper">
            <img  src="https://cloud-web-resources.s3.eu-central-1.amazonaws.com/404_page_resources/k2view-cloud-logo.png" class="logo">
          </div>
          <div class="oops">
            <img src="https://cloud-web-resources.s3.eu-central-1.amazonaws.com/404_page_resources/page-404.png" class="opss-404">		
          </div>
          <div class="text">
            <div class="pg-404-text">    
              <span class="Page-Not-Found">Your space is not responding.</span>
              <a href="{{ .Values.errorPage.secrets.K2_MANAGER_URL }}" class="go-back">Go to Cloud Manager &gt;</a>
            </div>
          </div>
          </div>
      </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-errors
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: nginx-errors
    app.kubernetes.io/part-of: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-errors
      app.kubernetes.io/part-of: ingress-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-errors
        app.kubernetes.io/part-of: ingress-nginx
    spec:
      serviceAccountName: restricted-sa
      containers:
      - name: nginx-error-server
        image: {{ .Values.errorPage.image }}
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
        # Mounting custom error page from configMap
        volumeMounts:
        - name: custom-error-pages
          mountPath: /www
        resources:
            limits:
              memory: 128Mi
              cpu: '0.2'
      # Mounting custom error page from configMap
      volumes:
      - name: custom-error-pages
        configMap:
          name: custom-error-pages
          items:
          - key: "custom_error"
            path: "404.html"
          - key: "custom_error"
            path: "503.html"
          - key: "custom_error"
            path: "502.html"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-errors
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: nginx-errors
    app.kubernetes.io/part-of: ingress-nginx
spec:
  selector:
    app.kubernetes.io/name: nginx-errors
    app.kubernetes.io/part-of: ingress-nginx
  ports:
  - port: 80
    targetPort: 8080
    name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-errors-ingress
  namespace: {{ .Values.namespace.name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/server-snippet: |
      add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
spec:
  tls:
  - hosts:
    - "*.{{ .Values.domain }}"
  rules:
  - host: "*.{{ .Values.domain }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginx-errors
            port:
              number: 80
{{- end }}