version: '3.9'
services:
  neo4j:
    image: ${NEO4J_IMAGE}
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      fab-net:
        ipv4_address: "${NEO4J_IP}"
    environment:
      - NEO4JLABS_PLUGINS=["graph-data-science"]
      - NEO4J_AUTH=neo4j/changeit
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
  fabric:
    image: "${STUDIO_IMAGE}"
    user: fabric
    depends_on:
      - neo4j
    ports:
      - "5124:5124"
      - "3213:3213"
    networks:
      fab-net:
        ipv4_address: "${FABRIC_IP}"
    environment:
      SPACE_NAME: "${SPACE_NAME}"
      NODE_ID: "${SPACE_NAME}"
      PROJECT_NAME: "${PROJECT_NAME}"
      PROJECT_DIR: "${PROJECT_DIR}"
      GIT_REPO: "${GIT_REPO}"
      GIT_BRANCH: "${GIT_BRANCH}"
      GIT_TOKEN: "${GIT_TOKEN}"
      CONFIG_UPDATE_FILE: /opt/apps/fabric/studio.config
    volumes:
      - ./studio.config:/opt/apps/fabric/studio.config
      - ./workspace/:/opt/apps/fabric/workspace/
    command: ["bash", "-l", "-c", "./docker-entrypoint.sh && tail -f /dev/null"]
    healthcheck:
      test: ["CMD", "/bin/bash", "/opt/apps/fabric/isAlive.sh"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s
networks:
  fab-net:
    driver: bridge
    ipam:
      config:
        - subnet: "${DOCKER_SUBNET}"
