kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: regional-pd
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-balanced
  replication-type: regional-pd
volumeBindingMode: Immediate
allowVolumeExpansion: true
allowedTopologies:
- matchLabelExpressions:
  - key: topology.gke.io/zone
    values:
    - "{{ .Values.region }}-a"
    - "{{ .Values.region }}-b"